/**
 * Home hero LCP assets — WebP responsive set + AVIF fallback (generated by scripts/optimize-images.mjs).
 */
import homeHeroDark480 from '../assets/HomeHero-480w.webp';
import homeHeroDark640 from '../assets/HomeHero-640w.webp';
import homeHeroDark768 from '../assets/HomeHero-768w.webp';
import homeHeroDark1024 from '../assets/HomeHero-1024w.webp';
import homeHeroDark1280 from '../assets/HomeHero-1280w.webp';
import homeHeroDark1536 from '../assets/HomeHero-1536w.webp';

import homeHeroLight480 from '../assets/HomeHero2-480w.webp';
import homeHeroLight640 from '../assets/HomeHero2-640w.webp';
import homeHeroLight768 from '../assets/HomeHero2-768w.webp';
import homeHeroLight1024 from '../assets/HomeHero2-1024w.webp';
import homeHeroLight1280 from '../assets/HomeHero2-1280w.webp';
import homeHeroLight1536 from '../assets/HomeHero2-1536w.webp';

import { buildResponsiveSrc } from './responsiveImage';

const darkSrcSet = {
  480: homeHeroDark480,
  640: homeHeroDark640,
  768: homeHeroDark768,
  1024: homeHeroDark1024,
  1280: homeHeroDark1280,
  1536: homeHeroDark1536,
};

const lightSrcSet = {
  480: homeHeroLight480,
  640: homeHeroLight640,
  768: homeHeroLight768,
  1024: homeHeroLight1024,
  1280: homeHeroLight1280,
  1536: homeHeroLight1536,
};

/** Public LCP URLs (copy-hero-lcp.mjs) — same file as index.html static hero + preload. */
export const LCP_HERO_DARK = '/hero/lcp-dark.webp';
export const LCP_HERO_LIGHT = '/hero/lcp-light.webp';

/** 640w default + srcset on desktop; mobile uses LCP URL only (no duplicate download). */
export const HOME_HERO_DARK = {
  webp: LCP_HERO_DARK,
  avif: undefined,
  ...buildResponsiveSrc(darkSrcSet, LCP_HERO_DARK),
  srcSetMap: darkSrcSet,
};

export const HOME_HERO_LIGHT = {
  webp: LCP_HERO_LIGHT,
  avif: undefined,
  ...buildResponsiveSrc(lightSrcSet, LCP_HERO_LIGHT),
  srcSetMap: lightSrcSet,
};

export const homeHeroBgDark = LCP_HERO_DARK;
export const homeHeroBgLight = LCP_HERO_LIGHT;
