/**
 * Home hero LCP assets — WebP responsive set + AVIF fallback (generated by scripts/optimize-images.mjs).
 */
import homeHeroDarkWebp from '../assets/HomeHero.webp';
import homeHeroDarkAvif from '../assets/HomeHero.avif';
import homeHeroDark480 from '../assets/HomeHero-480w.webp';
import homeHeroDark640 from '../assets/HomeHero-640w.webp';
import homeHeroDark768 from '../assets/HomeHero-768w.webp';
import homeHeroDark1024 from '../assets/HomeHero-1024w.webp';
import homeHeroDark1280 from '../assets/HomeHero-1280w.webp';
import homeHeroDark1536 from '../assets/HomeHero-1536w.webp';

import homeHeroLightWebp from '../assets/HomeHero2.webp';
import homeHeroLightAvif from '../assets/HomeHero2.avif';
import homeHeroLight480 from '../assets/HomeHero2-480w.webp';
import homeHeroLight640 from '../assets/HomeHero2-640w.webp';
import homeHeroLight768 from '../assets/HomeHero2-768w.webp';
import homeHeroLight1024 from '../assets/HomeHero2-1024w.webp';
import homeHeroLight1280 from '../assets/HomeHero2-1280w.webp';
import homeHeroLight1536 from '../assets/HomeHero2-1536w.webp';

import { buildResponsiveSrc } from './responsiveImage';

const darkSrcSet = {
  480: homeHeroDark480,
  640: homeHeroDark640,
  768: homeHeroDark768,
  1024: homeHeroDark1024,
  1280: homeHeroDark1280,
  1536: homeHeroDark1536,
};

const lightSrcSet = {
  480: homeHeroLight480,
  640: homeHeroLight640,
  768: homeHeroLight768,
  1024: homeHeroLight1024,
  1280: homeHeroLight1280,
  1536: homeHeroLight1536,
};

/** 640w default keeps LCP small; srcset upgrades on larger viewports. */
export const HOME_HERO_DARK = {
  webp: homeHeroDark640,
  avif: homeHeroDarkAvif,
  ...buildResponsiveSrc(darkSrcSet, homeHeroDark640),
  srcSetMap: darkSrcSet,
};

export const HOME_HERO_LIGHT = {
  webp: homeHeroLight640,
  avif: homeHeroLightAvif,
  ...buildResponsiveSrc(lightSrcSet, homeHeroLight640),
  srcSetMap: lightSrcSet,
};

/** Primary URL for link preload (active theme) — matches public/hero/lcp-*.webp */
export const homeHeroBgDark = homeHeroDark640;
export const homeHeroBgLight = homeHeroLight640;
