import { getLegalLastUpdatedLabel } from '../lib/legalLastUpdated';
import { pageHeroClass } from '../lib/cardThemeStyles';
import LegalContactFooter from './legal/LegalContactFooter';
import { SITE_CONTACT_EMAIL } from '../data/siteContact';

const sections = [
  {
    title: 'Overview',
    body: 'This Licenses page documents the software components, content rights, third-party integrations, and intellectual property frameworks that underpin the iFranchise platform. We are committed to transparency regarding the tools and technologies we use, and to honoring the licensing obligations associated with each.',
  },
  {
    title: 'Open Source Software',
    body: 'The iFranchise platform is built using open-source software components including React, Vite, Tailwind CSS, and various npm ecosystem packages. Each component is used in accordance with its respective license - including MIT, Apache 2.0, and BSD variants. A full dependency manifest is maintained in our technical documentation and is available upon request.',
  },
  {
    title: 'Proprietary Platform Software',
    body: 'All custom software, algorithms, data models, and platform logic developed by iFranchise are proprietary and protected under applicable copyright and trade secret law. Unauthorized reproduction, reverse engineering, decompilation, or distribution of any proprietary component is strictly prohibited.',
  },
  {
    title: 'Franchise Brand Content',
    body: 'Franchise brand names, logos, trademarks, promotional materials, and business descriptions displayed on the iFranchise marketplace remain the exclusive intellectual property of their respective brand owners. iFranchise operates as a marketplace facilitator and does not claim ownership of any brand-specific content. All brand content is displayed under license or with explicit permission from the respective brand.',
  },
  {
    title: 'Platform Content and Design',
    body: 'All original content created by iFranchise - including editorial copy, UI design elements, iconography, illustrations, and data compilations - is protected under Indian and international copyright law. Users are granted a limited, non-exclusive right to view and interact with this content solely for legitimate business evaluation purposes. Any reproduction, redistribution, or commercial use requires prior written consent.',
  },
  {
    title: 'Third-Party Service Integrations',
    body: 'iFranchise integrates with third-party services for payment processing, analytics, cloud infrastructure, communication, and mapping. These integrations are governed by the respective service providers\' terms of service and licensing agreements. iFranchise does not sublicense third-party services to users beyond what is necessary for platform functionality.',
  },
  {
    title: 'API Access and Usage',
    body: 'Access to any iFranchise API endpoints is subject to a separate API license agreement. Unauthorized access to, scraping of, or automated querying of platform APIs without a valid license is prohibited. Approved API partners must comply with rate limits, data handling requirements, and usage restrictions defined in their individual agreements.',
  },
  {
    title: 'User-Submitted Content',
    body: 'Content submitted by users - including franchise enquiry forms, profile information, reviews, and communications - remains the intellectual property of the submitting party. By submitting content to iFranchise, users grant us a worldwide, royalty-free, non-exclusive license to store, process, display, and use that content solely for the purpose of delivering platform services.',
  },
  {
    title: 'Trademarks',
    body: 'The iFranchise name, wordmark, logo, and associated brand identifiers are registered or common-law trademarks of iFranchise. Unauthorized use of these marks in any commercial context - including in domain names, advertising, or product names - is prohibited without explicit written authorization from iFranchise.',
  },
  {
    title: 'Data and Analytics',
    body: 'Aggregated, anonymized platform data and market insights generated by iFranchise are proprietary. This data may be used internally for product improvement, shared with franchise brand partners in aggregate form, or published as market research. Individual user data is never sold or shared in identifiable form without consent.',
  },
  {
    title: 'Geographic and Regulatory Compliance',
    body: 'iFranchise services are designed primarily for the Indian market and comply with applicable Indian regulatory frameworks including the Information Technology Act, 2000, and relevant data protection guidelines. Users accessing the platform from outside India are responsible for ensuring compliance with their local laws and regulations.',
  },
  {
    title: 'License Updates',
    body: `This Licenses page may be updated periodically to reflect changes in third-party dependencies, new integrations, regulatory requirements, or platform enhancements. Material changes will be communicated through the platform. For licensing inquiries or to request attribution details, contact ${SITE_CONTACT_EMAIL}.`,
  },
];

function LicensesPage() {
  return (
    <LegalPageLayout
      badge="Legal"
      title="Licenses"
      subtitle="Software licenses, content usage rights, third-party attributions, and intellectual property frameworks governing the iFranchise platform."
      sections={sections}
    />
  );
}

export default LicensesPage;

// -- Inlined LegalPageLayout --
/**
 * LegalPageLayout
 * Shared layout for Privacy Policy, Terms & Conditions, and Licenses pages.
 * Apple / Google documentation style - single-column, clean, enterprise-grade.
 */

function LegalSection({ index, title, body }) {
  return (
    <section className="border-b border-violet-500/20 py-6 last:border-0 sm:py-8">
      <div className="mb-3 flex flex-col gap-2 sm:flex-row sm:items-baseline sm:gap-5">
        <span className="w-6 shrink-0 pt-0.5 text-xs font-semibold tabular-nums text-white/60">
          {String(index + 1).padStart(2, '0')}
        </span>
        <h2 className="text-lg font-semibold leading-snug text-white sm:text-xl">
          {title}
        </h2>
      </div>
      <p className="text-[15px] leading-relaxed text-white sm:pl-11 sm:text-base">
        {body}
      </p>
    </section>
  );
}

function LegalPageLayout({ title, subtitle, sections, badge }) {
  return (
    <div className="legal-page relative z-10 min-h-screen overflow-x-hidden text-white">
      {/* Page Header */}
      <div className="border-b border-violet-500/20 card-premium-dark-inner rounded-none border-x-0 border-t-0">
        <div className="max-w-3xl mx-auto px-5 sm:px-8 py-14 sm:py-20">
          {badge && (
            <span className="inline-block text-xs font-semibold uppercase tracking-widest text-white/80 mb-5">
              {badge}
            </span>
          )}
          <h1 className={`${pageHeroClass(false)} mb-5`}>
            {title}
          </h1>
          <p className="text-base sm:text-lg text-white leading-relaxed max-w-2xl mb-6">
            {subtitle}
          </p>
          <p className="text-sm text-white">
            Last Updated: <span className="text-white font-medium">{getLegalLastUpdatedLabel()}</span>
          </p>
        </div>
      </div>

      {/* Document Body */}
      <div className="max-w-3xl mx-auto px-5 sm:px-8 py-10 sm:py-14">
        <div className="card-premium-dark overflow-hidden rounded-3xl p-5 shadow-[0_4px_24px_rgba(0,0,0,0.4)] sm:p-8 md:p-10">
          {sections.map((section, i) => (
            <LegalSection
              key={i}
              index={i}
              title={section.title}
              body={section.body}
            />
          ))}
        </div>

        <LegalContactFooter />
      </div>
    </div>
  );
}
