const sections = [
  {
    title: 'Overview',
    body: 'This Licenses page documents the software components, content rights, third-party integrations, and intellectual property frameworks that underpin the iFranchise platform. We are committed to transparency regarding the tools and technologies we use, and to honoring the licensing obligations associated with each.',
  },
  {
    title: 'Open Source Software',
    body: 'The iFranchise platform is built using open-source software components including React, Vite, Tailwind CSS, and various npm ecosystem packages. Each component is used in accordance with its respective license — including MIT, Apache 2.0, and BSD variants. A full dependency manifest is maintained in our technical documentation and is available upon request.',
  },
  {
    title: 'Proprietary Platform Software',
    body: 'All custom software, algorithms, data models, and platform logic developed by iFranchise are proprietary and protected under applicable copyright and trade secret law. Unauthorized reproduction, reverse engineering, decompilation, or distribution of any proprietary component is strictly prohibited.',
  },
  {
    title: 'Franchise Brand Content',
    body: 'Franchise brand names, logos, trademarks, promotional materials, and business descriptions displayed on the iFranchise marketplace remain the exclusive intellectual property of their respective brand owners. iFranchise operates as a marketplace facilitator and does not claim ownership of any brand-specific content. All brand content is displayed under license or with explicit permission from the respective brand.',
  },
  {
    title: 'Platform Content and Design',
    body: 'All original content created by iFranchise — including editorial copy, UI design elements, iconography, illustrations, and data compilations — is protected under Indian and international copyright law. Users are granted a limited, non-exclusive right to view and interact with this content solely for legitimate business evaluation purposes. Any reproduction, redistribution, or commercial use requires prior written consent.',
  },
  {
    title: 'Third-Party Service Integrations',
    body: 'iFranchise integrates with third-party services for payment processing, analytics, cloud infrastructure, communication, and mapping. These integrations are governed by the respective service providers\' terms of service and licensing agreements. iFranchise does not sublicense third-party services to users beyond what is necessary for platform functionality.',
  },
  {
    title: 'API Access and Usage',
    body: 'Access to any iFranchise API endpoints is subject to a separate API license agreement. Unauthorized access to, scraping of, or automated querying of platform APIs without a valid license is prohibited. Approved API partners must comply with rate limits, data handling requirements, and usage restrictions defined in their individual agreements.',
  },
  {
    title: 'User-Submitted Content',
    body: 'Content submitted by users — including franchise enquiry forms, profile information, reviews, and communications — remains the intellectual property of the submitting party. By submitting content to iFranchise, users grant us a worldwide, royalty-free, non-exclusive license to store, process, display, and use that content solely for the purpose of delivering platform services.',
  },
  {
    title: 'Trademarks',
    body: 'The iFranchise name, wordmark, logo, and associated brand identifiers are registered or common-law trademarks of iFranchise. Unauthorized use of these marks in any commercial context — including in domain names, advertising, or product names — is prohibited without explicit written authorization from iFranchise.',
  },
  {
    title: 'Data and Analytics',
    body: 'Aggregated, anonymized platform data and market insights generated by iFranchise are proprietary. This data may be used internally for product improvement, shared with franchise brand partners in aggregate form, or published as market research. Individual user data is never sold or shared in identifiable form without consent.',
  },
  {
    title: 'Geographic and Regulatory Compliance',
    body: 'iFranchise services are designed primarily for the Indian market and comply with applicable Indian regulatory frameworks including the Information Technology Act, 2000, and relevant data protection guidelines. Users accessing the platform from outside India are responsible for ensuring compliance with their local laws and regulations.',
  },
  {
    title: 'License Updates',
    body: 'This Licenses page may be updated periodically to reflect changes in third-party dependencies, new integrations, regulatory requirements, or platform enhancements. Material changes will be communicated through the platform. For licensing inquiries or to request attribution details, contact legal@ifranchise.in.',
  },
];

function LicensesPage() {
  return (
    <LegalPageLayout
      badge="Legal"
      title="Licenses"
      subtitle="Software licenses, content usage rights, third-party attributions, and intellectual property frameworks governing the iFranchise platform."
      sections={sections}
    />
  );
}

export default LicensesPage;

// ── Inlined LegalPageLayout ──
/**
 * LegalPageLayout
 * Shared layout for Privacy Policy, Terms & Conditions, and Licenses pages.
 * Apple / Google documentation style — single-column, clean, enterprise-grade.
 */

const LAST_UPDATED = 'April 30, 2026';

function LegalSection({ index, title, body }) {
  return (
    <section className="py-8 border-b border-violet-500/20 last:border-0">
      <div className="flex gap-5 items-baseline mb-3">
        <span className="text-xs font-semibold text-white/60 tabular-nums w-6 shrink-0 pt-0.5">
          {String(index + 1).padStart(2, '0')}
        </span>
        <h2 className="text-lg sm:text-xl font-semibold text-white leading-snug">
          {title}
        </h2>
      </div>
      <p className="text-[15px] sm:text-base text-white leading-relaxed pl-11">
        {body}
      </p>
    </section>
  );
}

function LegalPageLayout({ title, subtitle, sections, badge }) {
  return (
    <div className="legal-page min-h-screen relative z-10 text-white">
      {/* Page Header */}
      <div className="border-b border-violet-500/20 card-premium-dark-inner rounded-none border-x-0 border-t-0">
        <div className="max-w-3xl mx-auto px-5 sm:px-8 py-14 sm:py-20">
          {badge && (
            <span className="inline-block text-xs font-semibold uppercase tracking-widest text-white/80 mb-5">
              {badge}
            </span>
          )}
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-white tracking-tight leading-tight mb-5">
            {title}
          </h1>
          <p className="text-base sm:text-lg text-white leading-relaxed max-w-2xl mb-6">
            {subtitle}
          </p>
          <p className="text-sm text-white">
            Last Updated: <span className="text-white font-medium">{LAST_UPDATED}</span>
          </p>
        </div>
      </div>

      {/* Document Body */}
      <div className="max-w-3xl mx-auto px-5 sm:px-8 py-10 sm:py-14">
        <div className="card-premium-dark rounded-3xl p-6 sm:p-10 shadow-[0_4px_24px_rgba(0,0,0,0.4)]">
          {sections.map((section, i) => (
            <LegalSection
              key={i}
              index={i}
              title={section.title}
              body={section.body}
            />
          ))}
        </div>

        {/* Contact Footer */}
        <div className="mt-14 pt-10 border-t border-violet-500/20">
          <p className="text-sm font-semibold text-white mb-5">Questions about this document?</p>
          <div className="flex flex-col sm:flex-row gap-4 sm:gap-8">
            <a
              href="mailto:legal@ifranchise.in"
              className="inline-flex items-center gap-2 text-sm text-white hover:text-white transition-colors"
            >
              <svg className="w-4 h-4 shrink-0 text-violet-400/80" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 8l7.89 4.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              legal@ifranchise.in
            </a>
            <a
              href="tel:+919876543210"
              className="inline-flex items-center gap-2 text-sm text-white hover:text-white transition-colors"
            >
              <svg className="w-4 h-4 shrink-0 text-violet-400/80" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
              </svg>
              +91 98765 43210
            </a>
            <span className="inline-flex items-center gap-2 text-sm text-white">
              <svg className="w-4 h-4 shrink-0 text-violet-400/80" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
              Bangalore, Karnataka, India
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
